# Importing Numpy

In [2]:
import numpy as np

# The Basics

In [3]:
# a = np.array([1.0,2.0,3.0], int)
# a = np.array([1.0,2.0,3.0], dtype='float32')
a = np.array([1.0,2.0,3.0], dtype='int16')
print(a)

[1 2 3]


In [4]:
b = np.array([[1.0,2.0,3.0], [2.0,4.0,6.0]])
print(b)

[[1. 2. 3.]
 [2. 4. 6.]]


# Get what dimensional array it is

In [5]:
a.ndim

1

In [6]:
b.ndim

2

# Get Shape

In [7]:
a.shape

(3,)

In [8]:
b.shape

(2, 3)

# Get Data Type of Array

In [9]:
a.dtype

dtype('int16')

In [10]:
b.dtype

dtype('float64')

# Get size of Array

In [11]:
# gives the each array item size in bytes
a.itemsize

2

In [12]:
b.itemsize

8

In [13]:
# gives the total number of elements in the array
a.size

3

In [14]:
b.size

6

In [15]:
# Gives the total size of array in bytes
a.nbytes

6

In [16]:
b.nbytes

48

In [17]:
# Gives the total size of array in bytes (Another way)
a.size * a.itemsize

6

In [18]:
b.size * b.itemsize

48

# Access/Modify specific elements, rows, columns, etc

In [19]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
# Get a specific element - [row_index, column_index]
a[1,5]

13

In [21]:
# Get a specific column - [row_index_start:_row_index_end, column_index_start:column_index_end ]
# Here end index is exclusive that means end index will be the previous index
# all row and column index 2
a[:, 2]

array([ 3, 10])

In [22]:
# Getting stuffs in different format
# Get a specific column - [column_index_start:column_index_end:step_index]
# a[0, 1:6:2]
a[0, 1:-1:2]

array([2, 4, 6])

In [23]:
# modifying a specific element
a[1,5] = 20
print(a)

# modify a column value
a[:, 2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# 3D example

In [24]:
b = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
# Get specific element 
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [26]:
# modify
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Arrays

In [27]:
# zeros matrix
# np.zeros(5)
# np.zeros(5, int)
# np.zeros(5, dtype='int16')
# np.zeros((2,3))
np.zeros((3,3), int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
# ones matrix
np.ones((4,3,3), dtype="int32")

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [29]:
# Any other number matrix
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [30]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [31]:
# any other number full_like
np.full_like(a, 33)

array([[33, 33, 33, 33, 33, 33, 33],
       [33, 33, 33, 33, 33, 33, 33]])

In [32]:
# random decimel numbers
np.random.rand(4,2)

array([[0.27265127, 0.07791774],
       [0.8533704 , 0.84220968],
       [0.5763504 , 0.32820754],
       [0.74192127, 0.84145758]])

In [33]:
np.random.random_sample(a.shape)

array([[0.00603438, 0.864065  , 0.40383597, 0.21508676, 0.09199857,
        0.52749781, 0.49668775],
       [0.44074365, 0.44720475, 0.91624124, 0.50033113, 0.2175026 ,
        0.09546379, 0.59976484]])

In [34]:
# random int numebers
np.random.randint(7, size=(3,3))

array([[1, 3, 0],
       [2, 6, 5],
       [5, 3, 2]])

In [35]:
np.random.randint(4,8, size=(3,4))

array([[4, 5, 4, 7],
       [5, 6, 5, 7],
       [5, 6, 5, 5]])

In [36]:
# identity matrix
# np.identity(4)
np.identity(4, int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [37]:
# Repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [38]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [39]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


 # Have to print this shape
 # 1 1 1 1 1
 # 1 0 0 0 1
 # 1 0 9 0 1
 # 1 0 0 0 1
 # 1 1 1 1 1

In [40]:
arr = np.ones((5,5), int)
arr[1:4,1:4] = 0
arr[2,2] = 9
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [41]:
# another way
output = np.ones((5,5), int)
z = np.zeros((3,3), int)
z[1,1] = 9
# output[1:4, 1:4] = z
output[1:-1, 1:-1] = z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# Copying array into another array

In [42]:
# when one element changes it effects the other array also as both the array are pointing to the same array
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [43]:
# to actually copy we need to use the copy() method
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathematics

In [44]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [45]:
a + 2

array([3, 4, 5, 6])

In [46]:
a - 2

array([-1,  0,  1,  2])

In [47]:
a * 2

array([2, 4, 6, 8])

In [48]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [49]:
a ** a

array([  1,   4,  27, 256], dtype=int32)

In [50]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [51]:
a % 2

array([1, 0, 1, 0], dtype=int32)

In [52]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [53]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [54]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [55]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

# Linear Algebra

In [61]:
# matrix multiplication
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [65]:
# find determinant of a matrix
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [66]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
np.min(stats)

1

In [68]:
np.min(stats, axis=0)

array([1, 2, 3])

In [69]:
np.min(stats, axis=1)

array([1, 4])

In [70]:
np.max(stats, axis=1)

array([3, 6])

In [71]:
np.min(stats, axis=0)

array([1, 2, 3])

In [72]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [73]:
np.sum(stats, axis=1)

array([ 6, 15])

# Reorganizing Arrays

In [86]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

# after = before.reshape((4,2))
# after = before.reshape((8,1))
after = before.reshape((2,2,2))


print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [90]:
# vertical stacking matrices
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2, v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [94]:
# horizontal stacking matrices
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
# np.hstack((h1,h2))
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

In [99]:
# Load data from file
filedata = np.genfromtxt('data.txt', delimiter=',')
# filedata.astype('int32')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [102]:
# Boolean Masking and advanced indexing
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [103]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [105]:
# We can index with a list in NUMPY
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [106]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [107]:
np.any(filedata > 50, axis=1)

array([ True,  True,  True])

In [108]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [109]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [113]:
((filedata > 50) & (filedata <100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])